# Generated by Django 5.1.4 on 2025-07-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Nome")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "description",
                    models.CharField(max_length=1000, verbose_name="Descrição"),
                ),
                ("promotes_by", models.CharField(max_length=300, verbose_name="Nome")),
                ("local", models.CharField(max_length=300, verbose_name="Local")),
                ("state", models.CharField(max_length=2, verbose_name="Estado")),
                ("phone", models.CharField(max_length=11, verbose_name="Telefone")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                (
                    "event_link",
                    models.CharField(max_length=100, verbose_name="Link do evento"),
                ),
            ],
        ),
    ]
